[package]
name = "CP_scoreboard"
version = "0.1.0"
authors = ["Leo <leo881003@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "^0.4.6", features = ["serde"] }
config = "^0.9.2"
ncurses = "^5.99.0"
prettytable-rs = "^0.8.0"
reqwest = "^0.9.14"
