[package]
name = "CP_scoreboard"
version = "0.1.0"
authors = ["Leo <leo881003@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "^0.4.6", features = ["serde"] }
config = "^0.9.2"
cursive = "^0.11.1"
prettytable-rs = "^0.8.0"
reqwest = "^0.9.14"
cookie = { version = "^0.11.0", features = ["percent-encode"] }
serde_json = "^1.0.39"
term = "^0.5"