[package]
name = "FOJ_scoreboard"
version = "0.6.0"
authors = ["Leo <leo881003@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "^0.4.6", features = ["serde"] }
cursive = "^0.13"
# custom_error makes compile error on 1.7.1
custom_error = "=1.7.0"
prettytable-rs = "^0.8.0"
reqwest = "^0.9.14"
serde = { version = "^1.0.90", features = ["derive"] }
serde_json = "^1.0.39"
bincode = "^1.2"
toml = "^0.5"
futures = "^0.1.26"
tokio = "^0.1.19"
tokio-timer = "^0.2.10"
term = "^0.5"
log = "^0.4"
serde_repr = "0.1.5"
